#!/usr/bin/env node

var program = require('../vendor/node_modules/commander/');
var shell = require('../vendor/node_modules/shelljs/');
console.log(shell.ls());


program
  .version('0.0.1')
  .option('-u, --url [url]', 'A [url] to test', null)
  .parse(process.argv);

console.log('Testing: %s', program.url);
