#!/usr/bin/env node

var program = require('../vendor/node_modules/commander/');
var shell = require('../vendor/node_modules/shelljs/');
// require('../vendor/node_modules/phantomjs');

// phantomjs phantomquail.js http://quailpages/forms/simple-form.html && jsonpp results.js | less

// Change to the dist dir.
shell.cd(__dirname);
shell.cd('..');

program
  .version('0.0.1')
  .option('-u, --url [url]', 'A [url] to test', null)
  .parse(process.argv);

var phantomjsExec = './vendor/node_modules/phantomjs/bin/phantomjs';
var phantomEvaluator = './evaluator/phantom_evaluator.js';

var command = [phantomjsExec, phantomEvaluator, program.url].join(' ');
shell.exec(command, {
  async:true
}, function (code, output) {
  console.log('code: ' + code);
  console.log('output: ' + output);
});
